import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { parseFen } from '../game/fen'
import { reduceMove } from '../game/reducer'
import { allLegalMoves, gameStatus, isGameOver } from '../game/status'
import { algebraic } from '../game/coord'
import { RULES_STANDARD_CHESS, isRuleSetToken, rulesOf } from '../game/rules'
import { fastestMateIn, forcedMateMoves } from './mate'
import { bandOf, measureDifficulty } from './difficulty'
import { PUZZLE_SCHEMA } from './types'
import type { Puzzle, PuzzleSet } from './types'

/**
 * The **committed** puzzle set, re-proved against the rules.
 *
 * `mine.test.ts` proves a batch the miner just produced; this proves the artifact that
 * actually ships, which is a different guarantee — it catches a hand-edited file, a format
 * drift, or a set generated by an older miner whose criteria have since changed.
 *
 * Every puzzle is schema-checked; a deterministic **sample** is fully re-proved, because
 * proving one costs ~50 ms and the set is meant to grow. `PUZZLES_DEEP=1 npm run test`
 * proves every one of them — the same gate the deep perft counts use, for the same reason.
 */
const SET_PATH = 'puzzles/puzzles.v2.json'
const DEEP = process.env.PUZZLES_DEEP === '1'
const SAMPLE_EVERY = 5

const set: PuzzleSet = JSON.parse(readFileSync(SET_PATH, 'utf8'))
const sample = DEEP ? set.puzzles : set.puzzles.filter((_p, i) => i % SAMPLE_EVERY === 0)

describe('the committed puzzle set', () => {
  it('is not empty, and says how it was made', () => {
    expect(set.puzzles.length).toBeGreaterThan(0)
    expect(set.schema).toBe(PUZZLE_SCHEMA)
    expect(set.goals.length).toBeGreaterThan(0)
    expect(isRuleSetToken(set.ruleset)).toBe(true)
    // The seed is what makes the set reproducible; without it the file is unrepeatable.
    expect(Number.isInteger(set.seed)).toBe(true)
    expect(set.candidates).toBeGreaterThan(set.puzzles.length)
  })

  it('has a well-formed, uniquely identified record for every puzzle', () => {
    const ids = new Set<string>()
    for (const p of set.puzzles) {
      expect(p.schema).toBe(PUZZLE_SCHEMA)
      expect(set.goals).toContain(p.goal)
      expect(p.sideToMove).toBe('white')
      expect(p.unique).toBe(true)
      expect(typeof p.chessDifferential).toBe('string')
      expect(isRuleSetToken(p.ruleset)).toBe(true)
      expect(p.solution.from).toMatch(/^[a-h][1-8]$/)
      expect(p.solution.to).toMatch(/^[a-h][1-8]$/)
      expect(p.solution.coordinate).toBe(`${p.solution.from}-${p.solution.to}${p.solution.crossedSeam ? '*' : ''}`)
      expect(ids.has(p.id)).toBe(false)
      ids.add(p.id)
    }
  })

  it('never places a pawn on the first or last rank', () => {
    // An illegal position is not a hard puzzle. Read straight from the FEN, so a bug in
    // the placer cannot hide behind the miner's own checks.
    for (const p of set.puzzles) {
      const [ranks] = p.fen.split(' ')
      const rows = ranks!.split('/')
      expect(rows[0], `${p.id} has a pawn on rank 8`).not.toMatch(/[pP]/)
      expect(rows[7], `${p.id} has a pawn on rank 1`).not.toMatch(/[pP]/)
    }
  })

  it(`re-proves ${DEEP ? 'every' : 'a sample of'} puzzle: unique, forced, and no faster mate`, () => {
    for (const p of sample) {
      const state = parseFen(p.fen, rulesOf(p.ruleset))
      const goalMoves = p.goal === 'mate-in-3' ? 3 : 2
      expect(isGameOver(gameStatus(state)), `${p.id} is already over`).toBe(false)
      expect(fastestMateIn(state, goalMoves - 1), `${p.id} has a faster mate`).toBeNull()

      const solutions = forcedMateMoves(state, goalMoves)
      expect(solutions, `${p.id} must have exactly one solution`).toHaveLength(1)
      expect(algebraic(solutions[0]!.from)).toBe(p.solution.from)
      expect(algebraic(solutions[0]!.to)).toBe(p.solution.to)
      expect(solutions[0]!.crossedSeam).toBe(p.solution.crossedSeam)
    }
  }, 600_000)

  it('records a chess differential that matches re-solving the position as chess', () => {
    // The label the library's variety depends on. Re-derived rather than trusted, because
    // it is what tells a seam puzzle from an ordinary tactic — and since 2026-09-26 both
    // belong in the set, a wrong label is no longer caught by the puzzle simply vanishing.
    for (const p of sample) {
      const asChess = parseFen(p.fen, RULES_STANDARD_CHESS)
      if (isGameOver(gameStatus(asChess))) {
        expect(p.chessDifferential, `${p.id} is dead in chess`).toBe('dead-in-chess')
        continue
      }
      const goalMoves = p.goal === 'mate-in-3' ? 3 : 2
      const chessSolutions = forcedMateMoves(asChess, goalMoves)
      const faster = fastestMateIn(asChess, goalMoves - 1)
      const noMate = chessSolutions.length === 0 && faster === null

      if (p.chessDifferential === 'no-mate-in-chess') {
        expect(noMate, `${p.id} claims no mate in chess`).toBe(true)
      } else {
        expect(noMate, `${p.id} claims a mate exists in chess`).toBe(false)
      }
    }
  }, 600_000)

  it('re-derives the difficulty band from the position, so it cannot be hand-edited', () => {
    for (const p of sample) {
      const state = parseFen(p.fen, rulesOf(p.ruleset))
      const move = allLegalMoves(state, 'white').find(
        m => algebraic(m.from) === p.solution.from && algebraic(m.to) === p.solution.to,
      )!
      const features = measureDifficulty(state, move, p.goal === 'mate-in-3' ? 3 : 2)

      expect(features, `${p.id} features`).toEqual(p.features)
      expect(bandOf(features), `${p.id} band`).toBe(p.difficulty)
    }
  }, 600_000)

  it('records solutions that are legal moves of a white piece', () => {
    for (const p of sample) {
      const state = parseFen(p.fen, rulesOf(p.ruleset))
      const move = allLegalMoves(state, 'white').find(
        m => algebraic(m.from) === p.solution.from && algebraic(m.to) === p.solution.to,
      )

      expect(move, `${p.id}: ${p.solution.coordinate} must be legal`).toBeDefined()
      expect(reduceMove(state, move!), `${p.id}: the solution must be playable`).not.toBe(state)
    }
  }, 600_000)
})

describe('what the set is made of', () => {
  it('reports its composition, so a dull set is visible rather than assumed', () => {
    const byMaterial = new Map<string, number>()
    for (const p of set.puzzles) byMaterial.set(p.material, (byMaterial.get(p.material) ?? 0) + 1)
    const seam = set.puzzles.filter((p: Puzzle) => p.solution.crossedSeam).length

    // Printed, not asserted: these are facts about a mined artifact, and pinning them
    // would only break every time the set is regenerated with a different seed.
    console.log(
      `puzzle set: ${set.puzzles.length} puzzles from ${set.candidates} candidates, ` +
      `${seam} with a seam solution, by material ${[...byMaterial].map(([m, n]) => `${m}:${n}`).join(' ')}`,
    )
    expect(set.puzzles.length).toBeGreaterThan(0)
  })
})
