import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { parseFen } from '../game/fen'
import { reduceMove } from '../game/reducer'
import { allLegalMoves, gameStatus, isGameOver } from '../game/status'
import { algebraic } from '../game/coord'
import { RULES_STANDARD_CHESS, isRuleSetToken, rulesOf } from '../game/rules'
import { hasMateInOne, mateInTwoMoves } from './mate'
import { PUZZLE_SCHEMA } from './types'
import type { Puzzle, PuzzleSet } from './types'

/**
 * The **committed** puzzle set, re-proved against the rules.
 *
 * `mine.test.ts` proves a batch the miner just produced; this proves the artifact that
 * actually ships, which is a different guarantee — it catches a hand-edited file, a format
 * drift, or a set generated by an older miner whose criteria have since changed.
 *
 * Every puzzle is schema-checked; a deterministic **sample** is fully re-proved, because
 * proving one costs ~50 ms and the set is meant to grow. `PUZZLES_DEEP=1 npm run test`
 * proves every one of them — the same gate the deep perft counts use, for the same reason.
 */
const SET_PATH = 'puzzles/mate-in-2.v1.json'
const DEEP = process.env.PUZZLES_DEEP === '1'
const SAMPLE_EVERY = 5

const set: PuzzleSet = JSON.parse(readFileSync(SET_PATH, 'utf8'))
const sample = DEEP ? set.puzzles : set.puzzles.filter((_p, i) => i % SAMPLE_EVERY === 0)

describe('the committed puzzle set', () => {
  it('is not empty, and says how it was made', () => {
    expect(set.puzzles.length).toBeGreaterThan(0)
    expect(set.schema).toBe(PUZZLE_SCHEMA)
    expect(set.goal).toBe('mate-in-2')
    expect(isRuleSetToken(set.ruleset)).toBe(true)
    // The seed is what makes the set reproducible; without it the file is unrepeatable.
    expect(Number.isInteger(set.seed)).toBe(true)
    expect(set.candidates).toBeGreaterThan(set.puzzles.length)
  })

  it('has a well-formed, uniquely identified record for every puzzle', () => {
    const ids = new Set<string>()
    for (const p of set.puzzles) {
      expect(p.schema).toBe(PUZZLE_SCHEMA)
      expect(p.goal).toBe('mate-in-2')
      expect(p.sideToMove).toBe('white')
      expect(p.unique).toBe(true)
      expect(p.mateInChess).toBe(false)
      expect(isRuleSetToken(p.ruleset)).toBe(true)
      expect(p.solution.from).toMatch(/^[a-h][1-8]$/)
      expect(p.solution.to).toMatch(/^[a-h][1-8]$/)
      expect(p.solution.coordinate).toBe(`${p.solution.from}-${p.solution.to}${p.solution.crossedSeam ? '*' : ''}`)
      expect(ids.has(p.id)).toBe(false)
      ids.add(p.id)
    }
  })

  it('never places a pawn on the first or last rank', () => {
    // An illegal position is not a hard puzzle. Read straight from the FEN, so a bug in
    // the placer cannot hide behind the miner's own checks.
    for (const p of set.puzzles) {
      const [ranks] = p.fen.split(' ')
      const rows = ranks!.split('/')
      expect(rows[0], `${p.id} has a pawn on rank 8`).not.toMatch(/[pP]/)
      expect(rows[7], `${p.id} has a pawn on rank 1`).not.toMatch(/[pP]/)
    }
  })

  it(`re-proves ${DEEP ? 'every' : 'a sample of'} puzzle: unique, forced, and no faster mate`, () => {
    for (const p of sample) {
      const state = parseFen(p.fen, rulesOf(p.ruleset))
      expect(isGameOver(gameStatus(state)), `${p.id} is already over`).toBe(false)
      expect(hasMateInOne(state), `${p.id} has a faster mate`).toBe(false)

      const solutions = mateInTwoMoves(state)
      expect(solutions, `${p.id} must have exactly one solution`).toHaveLength(1)
      expect(algebraic(solutions[0]!.from)).toBe(p.solution.from)
      expect(algebraic(solutions[0]!.to)).toBe(p.solution.to)
      expect(solutions[0]!.crossedSeam).toBe(p.solution.crossedSeam)
    }
  }, 600_000)

  it(`is ${DEEP ? 'entirely' : 'demonstrably'} impossible in chess — the point of the whole set`, () => {
    for (const p of sample) {
      const asChess = parseFen(p.fen, RULES_STANDARD_CHESS)
      if (isGameOver(gameStatus(asChess))) continue // insufficient material in chess: still novel
      expect(hasMateInOne(asChess), `${p.id} is a mate in one in chess`).toBe(false)
      expect(mateInTwoMoves(asChess), `${p.id} is a mate in two in chess`).toHaveLength(0)
    }
  }, 600_000)

  it('records solutions that are legal moves of a white piece', () => {
    for (const p of sample) {
      const state = parseFen(p.fen, rulesOf(p.ruleset))
      const move = allLegalMoves(state, 'white').find(
        m => algebraic(m.from) === p.solution.from && algebraic(m.to) === p.solution.to,
      )

      expect(move, `${p.id}: ${p.solution.coordinate} must be legal`).toBeDefined()
      expect(reduceMove(state, move!), `${p.id}: the solution must be playable`).not.toBe(state)
    }
  }, 600_000)
})

describe('what the set is made of', () => {
  it('reports its composition, so a dull set is visible rather than assumed', () => {
    const byMaterial = new Map<string, number>()
    for (const p of set.puzzles) byMaterial.set(p.material, (byMaterial.get(p.material) ?? 0) + 1)
    const seam = set.puzzles.filter((p: Puzzle) => p.solution.crossedSeam).length

    // Printed, not asserted: these are facts about a mined artifact, and pinning them
    // would only break every time the set is regenerated with a different seed.
    console.log(
      `puzzle set: ${set.puzzles.length} puzzles from ${set.candidates} candidates, ` +
      `${seam} with a seam solution, by material ${[...byMaterial].map(([m, n]) => `${m}:${n}`).join(' ')}`,
    )
    expect(set.puzzles.length).toBeGreaterThan(0)
  })
})
