/**
 * THE SHIPPED PUZZLE SET — the committed artifact, loaded for the app.
 *
 * **What is this?** The bridge between `puzzles/mate-in-2.v1.json`, which the miner writes,
 * and the UI, which needs `GameState`s rather than records.
 *
 * **Why is it here?** So exactly one module knows where the set lives and what shape it
 * has. The JSON is data, not source: it is generated by `npm run mine:puzzles` from a
 * recorded seed, and regenerating it must not mean touching a component.
 *
 * **What is subtle?** A puzzle's `ruleset` is part of its identity, not decoration. The
 * same board under a different token is a different puzzle, usually with a different
 * answer — which is the whole premise of the set. So a position is never built with the
 * default rules; it is always built with the puzzle's own.
 */
import { parseFen } from '../game/fen'
import { parseRuleSetToken, rulesOf } from '../game/rules'
import type { GameState } from '../game/types'
import type { Puzzle, PuzzleSet } from './types'
import data from '../../puzzles/mate-in-2.v1.json'

/** The committed set. Typed on the way in, so a drifted file fails here rather than later. */
const SET = data as unknown as PuzzleSet

/** Every shipped puzzle, in mined order — stable, so "puzzle 3" means the same thing twice. */
export function allPuzzles(): readonly Puzzle[] {
  return SET.puzzles
}

/** How many there are, and what they were mined from. */
export function puzzleSetSummary(): { readonly count: number; readonly seam: number; readonly seed: number } {
  return {
    count: SET.puzzles.length,
    seam: SET.puzzles.filter(p => p.solution.crossedSeam).length,
    seed: SET.seed,
  }
}

/**
 * The position a puzzle starts from, under **its own** ruleset.
 *
 * @param puzzle The puzzle to open.
 * @returns A fresh `GameState`. Never shared between callers, so a UI can mutate its own
 *   copy of history without touching anyone else's.
 */
export function positionOf(puzzle: Puzzle): GameState {
  return parseFen(puzzle.fen, rulesOf(parseRuleSetToken(puzzle.ruleset)))
}

/**
 * Is this move the puzzle's answer?
 *
 * Compares origin and destination only. `crossedSeam` is deliberately excluded, exactly as
 * `reduceMove` excludes it: it is presentation, and dedupe guarantees at most one move per
 * destination, so two moves cannot share from/to and differ only in having crossed.
 * Promotion is compared because a different piece is a different move.
 */
export function isSolution(puzzle: Puzzle, move: { from: string; to: string; promotion: string | null }): boolean {
  return move.from === puzzle.solution.from &&
    move.to === puzzle.solution.to &&
    move.promotion === puzzle.solution.promotion
}
