/**
 * THE SHIPPED PUZZLE SET — the committed artifact, loaded for the app.
 *
 * **What is this?** The bridge between `puzzles/mate-in-2.v1.json`, which the miner writes,
 * and the UI, which needs `GameState`s rather than records.
 *
 * **Why is it here?** So exactly one module knows where the set lives and what shape it
 * has. The JSON is data, not source: it is generated by `npm run mine:puzzles` from a
 * recorded seed, and regenerating it must not mean touching a component.
 *
 * **What is subtle?** This module — and only this module — knows the library exists.
 * Per-puzzle helpers live in `puzzle.ts`, so a screen can open a puzzle passed to it
 * without depending on the shipped file being present.
 */
import { spreadOrder } from './diversity'
import type { Puzzle, PuzzleSet } from './types'
import data from '../../puzzles/puzzles.v3.json'

/** The committed set. Typed on the way in, so a drifted file fails here rather than later. */
const SET = data as unknown as PuzzleSet

/** Every shipped puzzle, in mined order. */
export function allPuzzles(): readonly Puzzle[] {
  return SET.puzzles
}

/**
 * The shipped puzzles in **play order** — spread so consecutive ones are unlike each other.
 *
 * Mined order clusters: the miner works one material set at a time, so it emits runs of
 * near-identical puzzles, and the first library had 33 copies of one motif. Playing in that
 * order means meeting four bishop mates in a row. Ordering by diversity is the cheap fix,
 * and it is the second use the novelty score was built for.
 *
 * Computed once: the order is a pure function of the set, and recomputing it per render
 * would reshuffle the library under the player.
 */
export function puzzlesInPlayOrder(): readonly Puzzle[] {
  playOrder ??= spreadOrder(SET.puzzles).map(i => SET.puzzles[i]!)
  return playOrder
}

let playOrder: readonly Puzzle[] | null = null

/**
 * Find a puzzle by its id, for a link that must keep pointing at the same puzzle.
 *
 * Indexes shift whenever the set is re-mined — a new goal or a relaxed criterion reorders
 * everything — so anything that must survive a re-mine (a bug report, an e2e fixture)
 * refers to a puzzle by id. The id is derived from the position and ruleset, so the same
 * puzzle keeps it.
 *
 * @returns Its index in the set, or `-1` if the set no longer contains it.
 */
export function indexOfPuzzleId(id: string): number {
  return puzzlesInPlayOrder().findIndex(p => p.id === id)
}

